export const RequestFavoritesCities  = {

    FETCH_FAVORITES_CITIES_PENDING: 'FETCH_FAVORITES_CITIES_PENDING',
    FETCH_FAVORITES_CITIES_SUCCESS: 'FETCH_FAVORITES_CITIES_SUCCESS',
    FETCH_FAVORITES_CITIES_FAILED: 'FETCH_FAVORITES_CITIES_FAILED',
}