export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';
export const UPDATE_CITY_NAME = 'UPDATE_CITY_NAME'
export const UPDATE_CITY_ID = 'UPDATE_CITY_ID'
export const THROW_ERROR = 'THROW_ERROR'


export const RequestSearchField = {

    FETCH_SEARCH_PENDING : 'FETCH_SEARCH_PENDING',
    FETCH_SEARCH_SUCCESS: 'FETCH_SEARCH_SUCCESS',
    FETCH_SEARCH_FAILED: 'FETCH_SEARCH_FAILED'
    

}

export const RequestCityById = {

    FETCH_CITY_PENDING : 'FETCH_CITY_PENDING',
    FETCH_CITY_SUCCESS: 'FETCH_CITY_SUCCESS',
    FETCH_CITY_FAILED: 'FETCH_CITY_FAILED'

}

export const RequestLocation = {

    FETCH_LOCATION_PENDING : 'FETCH_LOCATION_PENDING',
    FETCH_LOCATION_SUCCESS: 'FETCH_LOCATION_SUCCESS',
    FETCH_LOCATION_FAILED: 'FETCH_LOCATION_FAILED',
    FIND_LOCATION_FAILED:'FIND_LOCATION_FAILED'
}



export const RequestForecastById = {

    FETCH_FORECAST_PENDING : 'FETCH_FORECAST_PENDING',
    FETCH_FORECAST_SUCCESS: 'FETCH_FORECAST_SUCCESS',
    FETCH_FORECAST_FAILED: 'FETCH_FORECAST_FAILED'

}


export const SetFavoriteCity = {

    SET_FAVORITE_PENDING : ' SET_FAVORITE_PENDING',
    SET_FAVORITE_SUCCESS: ' SET_FAVORITE_SUCCESS',
    SET_FAVORITE_FAILED: ' SET_FAVORITE_FAILED'
}

export const GetFavoriteCityById = {

    GET_FAVORITE_PENDING : ' GET_FAVORITE_PENDING',
    GET_FAVORITE_SUCCESS: ' GET_FAVORITE_SUCCESS',
    GET_FAVORITE_FAILED: ' GET_FAVORITE_FAILED'
}